name: Deploy Website CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Save Original Git Author and Git Email
        run: |
          echo "git_email=$(git log --format='%ae' HEAD^!)" >> $GITHUB_ENV
          echo "git_name=$(git log --format='%an' HEAD^!)" >> $GITHUB_ENV

      - uses: actions/setup-node@v2.4.1

      - name: Cache Node Modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Build Dependencies
        run: npm ci

      - name: Run Build Script (Next static export)
        run: npm run build  

      - name: Copy build into docs/ on main
        run: |
          # delete old docs content
          rm -rf docs
          mkdir -p docs
          # copy static export (from ./out) into docs
          cp -r out/* docs/

          git config --local user.email "${{ env.git_email }}"
          git config --local user.name "${{ env.git_name }}"
          git add docs

          git diff --cached --quiet --exit-code && echo "no changes to website, exiting early" && exit 0

          git commit -m "Deploy site for $GITHUB_SHA"
          git push
