name: Deploy Website CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Save Original Git Author and Git Email
        run: |
          echo "git_email=$(git log --format='%ae' HEAD^!)" >> $GITHUB_ENV
          echo "git_name=$(git log --format='%an' HEAD^!)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Build Dependencies
        run: npm ci

      - name: Run Build Script (Next static export)
        run: npm run build   # ensure this produces ./out

      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: 'gh-built'

      - name: Push to gh-pages Branch
        run: |
          cd gh-built
          git rm -rf .
          git clean -fxd
          rsync -av --exclude 'gh-built' ../out/ .
          git add .
          git config --local user.email "${{ env.git_email }}"
          git config --local user.name "${{ env.git_name }}"
          git diff --cached --quiet --exit-code && echo "no changes to website, exiting early" && exit 0
          git commit -m "corresponding commit: $GITHUB_SHA"
          git push
